name-template: '$INPUT_VERSION'
tag-template: 'v$INPUT_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: 'New'
    labels:
     - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'maintenance'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Dependency Updates'
    labels:
    - 'dependencies'