name: Release

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: patrickjahns/version-drafter-action@master
        id: version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: release-drafter/release-drafter@master
        with:
          version: steps.version.outputs.next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}